apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    managed_by: dso
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    application: nginx-app
